import assert from 'node:assert/strict';
import fs from 'node:fs';
import {chromium} from 'playwright-core';
const browser = await chromium.launch({headless:true,args:['--no-sandbox']});
const base = 'http://127.0.0.1:5079';
const errors=[];
try {
 const staff = await browser.newContext({viewport:{width:375,height:812}});
 const page = await staff.newPage();
 page.on('pageerror',e=>errors.push(e.message));
 page.on('console',m=>{if(m.type()==='error'&&m.text().includes('Content Security Policy'))errors.push(m.text());});
 await page.goto(base+'/auth/login');
 const consent=page.locator('#ox-privacy-banner [data-privacy-reject]');if(await consent.isVisible())await consent.click();
 await page.locator('[name=email]').fill('super_admin@test.invalid');
 await page.locator('[name=password]').fill('qa-only-password');
 await page.locator('button[type=submit]').click();
 await page.waitForURL('**/superadmin/dashboard');
 await page.getByRole('button',{name:'Activar tienda privada',exact:true}).click();
 await page.waitForURL('**/superadmin/config?section=acceso');
 assert.equal(await page.locator('[name=ACCESO_CLIENTES_REGISTRADOS]').inputValue(),'1');
 assert.equal(await page.locator('[name=ACCESO_CLIENTES_REGISTRADOS]').isEnabled(),true);
 const customer = await browser.newContext({viewport:{width:375,height:812}});
 const client = await customer.newPage();
 await client.goto(base+'/');await client.waitForURL('**/acceso');
 assert.equal((await customer.request.get(base+'/manifest.webmanifest')).status(),403);
 await client.locator('[name=telefono]').fill('+34600000000');
 await client.getByRole('button',{name:'Recibir código'}).click();
 await client.locator('[name=codigo]').waitFor();
 await client.locator('[name=codigo]').fill(fs.readFileSync('/tmp/parcerito-flow-qa-otp','utf8'));
 await client.getByRole('button',{name:'Entrar',exact:true}).click();
 await client.waitForURL(base+'/');
 assert.equal((await customer.request.get(base+'/manifest.webmanifest')).status(),200);
 // Caduca la sesión de compra; se conserva únicamente la identidad del navegador.
 const deviceCookies=(await customer.cookies()).filter(cookie=>cookie.name==='oxidian_device');
 assert.equal(deviceCookies.length,1);
 await customer.clearCookies(); await customer.addCookies(deviceCookies);
 assert.equal((await customer.request.get(base+'/manifest.webmanifest')).status(),403);
 await client.goto(base+'/acceso');
 await client.locator('[name=telefono]').fill('+34600000000');
 await client.getByRole('button',{name:'Recibir código'}).click();
 await client.locator('[name=codigo]').waitFor();
 await client.locator('[name=codigo]').fill(fs.readFileSync('/tmp/parcerito-flow-qa-otp','utf8'));
 await client.getByRole('button',{name:'Entrar',exact:true}).click();
 await client.waitForURL(base+'/');
 assert.equal((await customer.request.get(base+'/manifest.webmanifest')).status(),200);
 const other = await browser.newContext();
 assert.equal((await other.request.get(base+'/manifest.webmanifest')).status(),403);
 await page.goto(base+'/superadmin/dashboard');
 await page.getByRole('button',{name:'Hacer pública',exact:true}).click();
 await page.waitForURL('**/superadmin/config?section=acceso');
 assert.equal(await page.locator('[name=ACCESO_CLIENTES_REGISTRADOS]').inputValue(),'0');
 assert.equal((await other.request.get(base+'/manifest.webmanifest')).status(),200);
 await page.goto(base+'/admin/delivery/franjas/nueva');
 assert.equal(await page.locator('[name=fecha]').count(),1);
 const date = new Date(); date.setDate(date.getDate()+2);
 const dateValue = date.toISOString().slice(0,10);
 for(const [start,end] of [['13:00','14:00'],['19:00','20:00']]) {
   await page.goto(base+'/admin/delivery/franjas/nueva');
   await page.locator('[name=fecha]').fill(dateValue);
   await page.locator('[name=hora_inicio]').fill(start);
   await page.locator('[name=hora_fin]').fill(end);
   await page.getByRole('button',{name:'Crear franja',exact:false}).click();
   await page.waitForURL('**/admin/delivery/franjas/panel');
 }
 await page.locator('.df-mode-form [name=modo]').selectOption('mixto');
 await page.getByRole('button',{name:'Aplicar modalidad'}).click();
 await page.waitForURL('**/admin/delivery/franjas/panel');
 const slotsResponse=await customer.request.get(base+'/api/delivery/franjas-disponibles');
 assert.equal(slotsResponse.status(),200);
 assert.equal((await slotsResponse.json()).franjas.filter(s=>s.fecha===dateValue).length,2);
 await client.goto(base+'/producto/1');
 const customerConsent=client.locator('#ox-privacy-banner [data-privacy-reject]');
 if(await customerConsent.isVisible())await customerConsent.click();
 await client.getByRole('button',{name:'Añadir Mango QA',exact:true}).click();
 await client.locator('.pd-extra-qty').fill('1');
 const added = client.waitForResponse(r=>r.url().includes('/carrito/agregar/') && r.request().method()==='POST');
 await client.locator('#pd-add-form button[type=submit]').click();
 const addResponse=await added; assert.equal(addResponse.status(),200);
 await addResponse.finished();
 await client.goto(base+'/carrito');
 assert.match(await client.locator('main').innerText(),/Mango QA/);
 assert.match(await client.locator('main').innerText(),/Queso QA/);
 await client.goto(base+'/checkout');
 await client.locator('[name=tipo_entrega_cliente][value=delivery]').check();
 await client.locator('[name=delivery_plan_ui][value=franja]').check();
 await client.locator('#franjas-day').selectOption(dateValue);
 await client.locator('[name=delivery_slot_ui]').nth(1).check();
 assert.ok(await client.locator('#franjas-slot-id').inputValue());
 assert.match(await client.locator('#franjas-slot-selected').innerText(),/19:00/);
 await client.locator('[name=tipo_entrega_cliente][value=recogida]').check();
 assert.equal(await client.locator('#franjas-slot-id').inputValue(),'');
 await client.locator('[name=tipo_entrega_cliente][value=delivery]').check();
 assert.equal(await client.locator('#franjas-slot-id').inputValue(),'');
 await client.goto(base+'/producto/'+fs.readFileSync('/tmp/parcerito-flow-qa-combo','utf8'));
 await client.locator('.combo-sel-qty').fill('2');
 await client.locator('.combo-sel-qty').dispatchEvent('input');
 const comboAdded=client.waitForResponse(r=>r.url().includes('/carrito/agregar/')&&r.request().method()==='POST');
 await client.locator('#pd-add-form button[type=submit]').click();
 await (await comboAdded).finished();
 await client.goto(base+'/carrito');
 assert.match(await client.locator('main').innerText(),/Combo completo QA/);
 assert.match(await client.locator('main').innerText(),/Bebida combo QA/);
 for(const [role,route] of [['cocina','/preparador/franjas'],['repartidor','/repartidor/franjas/panel']]) {
   const context=await browser.newContext({viewport:{width:320,height:740}});
   const work=await context.newPage();
   work.on('pageerror',e=>errors.push(role+': '+e.message));
   work.on('console',m=>{if(m.type()==='error'&&m.text().includes('Content Security Policy'))errors.push(role+': '+m.text());});
   await work.goto(base+'/auth/login');
   const privacy=work.locator('#ox-privacy-banner [data-privacy-reject]');
   if(await privacy.isVisible())await privacy.click();
   await work.locator('[name=email]').fill(role+'@test.invalid');
   await work.locator('[name=password]').fill('qa-only-password');
   await work.locator('button[type=submit]').click();
   await work.waitForURL(url=>!url.pathname.startsWith('/auth/'));
   await work.goto(base+route);
   assert.equal(await work.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,role+' overflow');
   await work.screenshot({path:'/tmp/parcerito-flow-'+role+'.png',fullPage:true});
   if(role==='repartidor') {
     await work.goto(base+'/repartidor/franjas/'+fs.readFileSync('/tmp/parcerito-flow-qa-slot','utf8')+'/pedidos-panel');
     assert.match(await work.locator('.fp-order-money').first().innerText(),/Cobrar al entregar: €10.00/);
     await work.locator('.fp-order-content summary').first().click();
     assert.equal(await work.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'contenido franja overflow');
     await work.screenshot({path:'/tmp/parcerito-flow-repartidor-carga.png',fullPage:true});
   }
   await context.close();
 }
 await page.setViewportSize({width:320,height:740});
 await page.goto(base+'/superadmin/dashboard');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'superadmin overflow');
 await page.screenshot({path:'/tmp/parcerito-flow-superadmin.png',fullPage:true});
 assert.deepEqual(errors,[]);
 console.log('Navegador real + CSRF + CSP: activar/desactivar, solicitar/verificar OTP, manifiesto y planificación con módulo apagado OK');
} finally { await browser.close(); }
